### PR TITLE
Auto-focus repeating task by firebase functions

### LINKED ISSUE #333: Overdue Repeating Tasks Don't Get Focused
**Describe the bug**
Normally, when the due date of a task arrives, it is automatically focused. Thus, when the task becomes overdue, the task will be in your focus with the red exclamation mark.
However, when the due date of a non-forked instance of a repeating task arrives, nothing happens. If the due date passes, then the instance just disappears off your feed entirely.

Blocks #313 

**To Reproduce**
Create a repeating task where there is an instance tomorrow. Come back in 2 days. Note that nothing is in focus and there is no indication you had a task due yesterday.

### PR DESCRIPTION
**Pull request by SamChou19815**
### Summary 

Close #333, our last open issue.

Implemented via a firebase function that auto focuses the repeating task by forking it. It reuses the existing common util function to tell whether today is on the repeating tasks' repetition schedule.

### Test Plan 

I created a repeating task that repeats on today, and run the function manually. It indeed got focused.

### CODE REVIEW

File: functions/src/focus-today-task.ts [hunk 1]
```diff
@@ -18,4 +22,56 @@ const focusTasksThatAreDueToday = async (): Promise<void> => {
   batch.commit();
 };
 
+const focusRepeatingTasksThatAreDueToday = async (): Promise<void> => {
+  const todayAtZero = new Date();
+  todayAtZero.setHours(0, 0, 0, 0);
+  const querySnapsot = await database
```
Comment (meganyin13) [inline functions/src/focus-today-task.ts:28]: I think you mean `querySnapshot`

**Review by meganyin13 — APPROVED** [review]
