### PR TITLE
Adjust prelim and final URLs and fix parser for FA20

### LINKED ISSUE #510: Make course-info script fetch FA20 final info when Cornell releases it

### PR DESCRIPTION
**Pull request by ptwu**
### Summary 

This pull request uncomments the prelim parsing code, as the prelim schedule has been posted on the registrar [here
](https://registrar.cornell.edu/exams/fall-prelim-exam-schedule). The format of the exam listings has also changed, and the HTML parser has been updated accordingly as explained below.

We can't add finals, as the registrar doesn't have this data yet.

- [x] fixes #510  (at least partially since we're uncertain if the registrar will provide finals data at all) 

While the spring prelim schedule from SP20 is no longer accessible, I used archive.org to find a cached version of the page. Previously, dates were in the format `MM/DD/YYYY` for each class, but now they are in the format `DAY_OF_WEEK DD MONTH_NAME`. The HTML parser has been updated accordingly to create a Date object that corresponds to the new date format.

SP20
image

FA20
image

### Test Plan 

Run the bash script in `/course-info` by running `./run` in the directory. See that no errors occur. You can cross-check the generated `.json` file to see if the `examTimes` field for a certain class object is defined. For example, CS 3110 has a prelim this coming Sunday, and its exam time has been populated.

image

### CODE REVIEW

**Comment by SamChou19815** [comment]
> [tssa]
> 
> No notable changes.

tssa doesn't support analyzing files not belonging to yarn workspace :(
I think it will be fixed once we fixed #552.

File: course-info/src/fetch-exam.ts [hunk 1]
```diff
@@ -16,18 +16,11 @@ async function fetchExamText(url: string): Promise<string> {
...
-    if (s !== '') {
-      datetimeString = s;
-      break;
-    }
-  }
-  const date = new Date(datetimeString);
+  const dateTimeString = `${segments[3]} ${segments[4]} ${currentYear}`;
+  const date = new Date(dateTimeString);
   date.setFullYear(currentYear);
   date.setHours(19, 30); // 7:30 prelim time
```
Comment (SamChou19815) [inline course-info/src/fetch-exam.ts:25]: the screenshot shows some exams at 4:00PM, so I guess we should somehow change this?

Comment (ptwu) [reply course-info/src/fetch-exam.ts]: Done.

**Review by SamChou19815 — APPROVED** [review]
ashipshipping-shipshippingshipping-ships-a-ship-shipping-ship-shipping-shipping-ships
