### PR TITLE
Fix frontend to work as expected after Task owner migration

### LINKED ISSUE #581: Migrate all string owner to string array owner
We need string array owner for all tasks to ensure that we can have a single, unified query that can fetch all tasks that can be displayed in personal view.

- [x] Create a script that can convert all existing data to string array.
- [x] Fix relevant code in the `frontend` package
- [x] Fix relevant code in the `functions` package

### PR DESCRIPTION
**Pull request by ptwu**
### Summary 

Merging in #607 and #608 and applying the Firebase function from #607 results in some issues. namely, the change to the `FirestoreCommon` type, which assumes that every firestore document now has an owner field of type `string[]`. However, this only applies to tasks - other entities will still have singular owners. As a result, subtasks and tags were not being shown.

This PR also introduces new security rules to fit the new `owner` definition for tasks, and fixes the `mergeWithOwner` function for subtasks, since subtasks still have singular owners.

- [x] fixes #581

### Test Plan 

See that frontend on staging should display everything as normally intended: subtasks for tasks with correct tags, group icons have the correct background colors:

image

### CODE REVIEW

**Comment by SamChou19815** [comment]
@ptwu I think the creating task doesn't work is due to this bad default value:

https://github.com/cornell-dti/samwise/blob/5408801f9a7133b27fa48477978a8ea0e77fd767/frontend/src/components/TaskCreator/index.tsx#L58

and there is an editOwner function that is never called:

https://github.com/cornell-dti/samwise/blob/5408801f9a7133b27fa48477978a8ea0e77fd767/frontend/src/components/TaskCreator/index.tsx#L200-L206

**Comment by ptwu** [comment]
> @ptwu I think the creating task doesn't work is due to this bad default value:
> 
> https://github.com/cornell-dti/samwise/blob/5408801f9a7133b27fa48477978a8ea0e77fd767/frontend/src/components/TaskCreator/index.tsx#L58
> 
> and there is an editOwner function that is never called:
> 
> https://github.com/cornell-dti/samwise/blob/5408801f9a7133b27fa48477978a8ea0e77fd767/frontend/src/components/TaskCreator/index.tsx#L200-L206

I removed the `editOwner` function because it was unused, and it assumes that the `owner` field is a singular value. Checking out the git blame shows that it was introduced by Pi here in #497. 

The old default value was the empty string. I don't think this is the problem since the default value is handled in `actions.ts` here
https://github.com/cornell-dti/samwise/blob/9b0ede85825aaf0c5346b3c3239ae1c99d6e5d74/frontend/src/firebase/actions.ts#L127

My guess is that there might be an error in the security rules for creating a task.

**Comment by SamChou19815** [comment]
@ptwu here is the problem:

https://github.com/cornell-dti/samwise/blob/9b0ede85825aaf0c5346b3c3239ae1c99d6e5d74/frontend/src/firebase/actions.ts#L127

Screen Shot 2020-10-23 at 12 23 27

**Comment by ptwu** [comment]
> @ptwu here is the problem:
> 
> https://github.com/cornell-dti/samwise/blob/9b0ede85825aaf0c5346b3c3239ae1c99d6e5d74/frontend/src/firebase/actions.ts#L127
> 
> Screen Shot 2020-10-23 at 12 23 27

image

**Comment by SamChou19815** [comment]
Loop in @pihucode as well. I think it's a bad idea to use `''` as the special value to decide whether we should use your own email as default owner. It is not obvious from the type signature. A better alternative is to use `readonly string[] | null` or `readonly string[] | undefined` where the `null` case means that we should use default owner.

**Comment by ptwu** [comment]
> Loop in @pihucode as well. I think it's a bad idea to use `''` as the special value to decide whether we should use your own email as default owner. It is not obvious from the type signature. A better alternative is to use `readonly string[] | null` or `readonly string[] | undefined` where the `null` case means that we should use default owner.

We can introduce this in an upcoming PR, since the goal here is to just get things working again 😢.

File: common/types/firestore-types.ts [hunk 1]
```diff
@@ -2,7 +2,7 @@ import { firestore } from 'firebase/app';
 import { RepeatingPattern } from './store-types';
 
 export type FirestoreCommon = {
-  readonly owner: readonly string[];
+  readonly owner: string | readonly string[];
```
Comment (SamChou19815) [inline common/types/firestore-types.ts:5]: I can accept this for now to unbreak dev. But we should really move `owner` out of `FirestoreCommon`. Otherwise I will be able to put a string array into a `FirestoreTag`.

**Review by SamChou19815 — APPROVED** [review]
only one non push blocking nit, otherwise LGTM
